### PR TITLE
SecurityPolicyDSC: Add FUTURE as Kerberos Encryption Type. Fixes #66

### LINKED ISSUE #66: Network_security_Configure_encryption_types_allowed_for_Kerberos
I noticed that this SecurityOption does not allow for 'Future encryption types' to be selected.

```
    "Network_security_Configure_encryption_types_allowed_for_Kerberos" = @{    
        Value   = "MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters\SupportedEncryptionTypes"
        Section = 'Registry Values'
        Option  = @{
            DES_CBC_CRC  = '4,1'
            DES_CBC_MD5  = '4,2'
            RC4_HMAC_MD5 = '4,4'
            AES128_HMAC_SHA1  = '4,8'
            AES256_HMAC_SHA1  = '4,16'           
        }
    } 

```

But this article from Microsoft explains how to enable that setting.
[(https://blogs.technet.microsoft.com/petergu/2013/04/14/interpreting-the-supportedencryptiontypes-registry-key/)]

Any plans to include this setting?

### PR DESCRIPTION
**Pull request by russelltomkins**
Allows the selection of "FUTURE" as a valid Encryption Type for the "Network_security_Configure_encryption_types_allowed_for_Kerberos" security option.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/securitypolicydsc/93)

### CODE REVIEW

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 123 at r1](https://reviewable.io/reviews/powershell/securitypolicydsc/93#-LDk--9WBvWUkDXvnlRt:-LDk--9WBvWUkDXvnlRu:b-7vfi3p) ([raw file](https://github.com/powershell/securitypolicydsc/blob/4318fb1803dd76dedc7b058cc6b0ee9b05d33842/README.md#L123)):*
> ```Markdown
> * **Network_security_Allow_LocalSystem_NULL_session_fallback**
> * **Network_Security_Allow_PKU2U_authentication_requests_to_this_computer_to_use_online_identities**
> * **Network_security_Configure_encryption_types_allowed_for_Kerberos**
> ```

Can we change to this (as per issue #71). Only this row, so we start somewhere. :slightly_smiling_face: 

```
* **`[String]` Network_security_Configure_encryption_types_allowed_for_Kerberos** _(Write)_: Please see above link for description. { DES_CBC_CRC | DES_CBC_MD5 | RC4_HMAC_MD5 | AES128_HMAC_SHA1 | AES256_HMAC_SHA1 | FUTURE }
```

Please also explain here when the value Future should be used.

---

*[README.md, line 166 at r1](https://reviewable.io/reviews/powershell/securitypolicydsc/93#-LDk-0u1CI0aZb5qHSLV:-LDk-0u1CI0aZb5qHSLW:b-t7es7t) ([raw file](https://github.com/powershell/securitypolicydsc/blob/4318fb1803dd76dedc7b058cc6b0ee9b05d33842/README.md#L166)):*
> ```Markdown
>   * Refactored the SID translation process to not throw a terminating error when called from Test-TargetResource
>   * Updated verbose message during the SID translation process to identify the policy where an orphaned SID exists
>   * Added the EType "FUTURE" to the security option "Network_security_Configure_encryption_types_allowed_for_Kerberos"
> ```

We should escape underscores here `\_`

---

*[DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.psm1, line 354 at r1](https://reviewable.io/reviews/powershell/securitypolicydsc/93#-LDk0Ges-3242vhqVll4:-LDk0Ges-3242vhqVll5:b-efcmgs) ([raw file](https://github.com/powershell/securitypolicydsc/blob/4318fb1803dd76dedc7b058cc6b0ee9b05d33842/DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.psm1#L354)):*
> ```PowerShell
> 
>         [Parameter()]
>         [ValidateSet("DES_CBC_CRC", "DES_CBC_MD5", "RC4_HMAC_MD5", "AES128_HMAC_SHA1", "AES256_HMAC_SHA1", "FUTURE")]
> ```

Would you mind changing all of these to single quotes?

---

*[DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.psm1, line 862 at r1](https://reviewable.io/reviews/powershell/securitypolicydsc/93#-LDk0C2d2p7mCDAOwzJ6:-LDk0C2d2p7mCDAOwzJ7:b-efcmgs) ([raw file](https://github.com/powershell/securitypolicydsc/blob/4318fb1803dd76dedc7b058cc6b0ee9b05d33842/DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.psm1#L862)):*
> ```PowerShell
> 
>         [Parameter()]
>         [ValidateSet("DES_CBC_CRC","DES_CBC_MD5","RC4_HMAC_MD5","AES128_HMAC_SHA1","AES256_HMAC_SHA1","FUTURE")]
> ```

Would you mind changing all of these to single quotes?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/securitypolicydsc/93)*

**Comment by russelltomkins** [comment]
formatting updated along with documentation updates for all options as per the validation options in the associated psd1 files.

**Comment by johlju** [comment]
Awesome work you did here with the entire README! Far and beyond what you had too! Thank you! :smiley: :bowing_man: 

Just a comments with few tiny changes to make it look even better. Now when we are on track! :slightly_smiling_face: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[README.md, line 60 at r2](https://reviewable.io/reviews/powershell/securitypolicydsc/93#-LE9zzso72VaPL96tIPn:-LE9zzso72VaPL96tIPo:b3rxncm) ([raw file](https://github.com/powershell/securitypolicydsc/blob/fa643eb082891f1226d4ced08d21962ed6184366/README.md#L60)):*
> ```Markdown
> to ensure the resource configuration instance is unique.
> 
> ## For explanation of below settings, please consult [Security Options Reference]https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/jj852268(v%3dws.11).
> ```

Can we move this above the Name parameter and change this to **bold** instead of a section header?

Something like this maybe? (same for the other resource is possible).

```
## SecurityOption

**For explanation of below settings, please consult [Security Options Reference]https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/jj852268(v%3dws.11).**

* **Name**: Name of security option configuration. This is not used during the configuration process but needed
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/securitypolicydsc/93#-:-LEA-U2c1tDbmmi3qXmf:b-81jmxy)*

**Comment by russelltomkins** [comment]
Just for clarification, were you hoping to have the full URL visible? or did you miss the () like I did in one of the links?

**Comment by johlju** [comment]
@russelltomkins Ah sorry, I missed the parenthesis! Didn't see that, good catch! Thanks for questioning that 🙂

**Comment by johlju** [comment]
I it wasn't clear, please use parenthesis 😃

**Comment by russelltomkins** [comment]
@johlju cool, just wanted to confirm :)

**Comment by johlju** [comment]
@russelltomkins Could you also add (to some description or similar) when the 'FUTURE' value should be used? I commented on that before, but I apparently resolved it without checking if it was done. :)

**Comment by russelltomkins** [comment]
@johlju It's in the reference link. Do you want to add it in the readme.md as well? Going to get quite busy if we add verbiage for every setting for every option. Maybe in the version update line item?

**Comment by johlju** [comment]
@russelltomkins Let's leave it in the reference link as the rest. Good as-is.

**Comment by johlju** [comment]
Please look att the failing test; https://ci.appveyor.com/project/PowerShell/securitypolicydsc/build/1.0.302.0#L34

**Comment by dancs85** [comment]
Did the AppVeyor test only fail because the README.md was missing a newline at the end?
https://ci.appveyor.com/project/PowerShell/securitypolicydsc/build/1.0.302.0#L34

This looks like it was fixed the same day:
https://github.com/PowerShell/SecurityPolicyDsc/commit/f38ec08f3d3711beb5b69bd7f261e521ce4e1679#diff-04c6e90faac2675aa89e2176d2eec7d8

Can the test be re-run?

**Pull request merged**
