### PR TITLE
SecurityPolicyDsc: Move Change Log to CHANGELOG.md and Add Build/Code Coverage Badges

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

To conform with other Dsc GitHub repositories, this PR moves the change log to a separate `CHANGELOG.md` file and adds AppVeyor Build and Code Coverage badges for the master and dev branches to the `README.md` file.

The `PULL_REQUEST_TEMPLATE.md` file has also been updated with the new location of the change log.

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/securitypolicydsc/133)

### CODE REVIEW

**Comment by X-Guardian** [comment]
Can someone review this PR?

**Comment by X-Guardian** [comment]
Hi @johlju, are you able to finish the review of this PR?

**Comment by johlju** [comment]
Yep, I can, but later this week I hope I can get to it. 🙂

**Comment by X-Guardian** [comment]
Cheers, that's great.

**Comment by X-Guardian** [comment]
Hi @johlju, are you able to finish the review of this PR? I have another bigger PR that greatly improves the documentation in this module that I will submit once this is merged.

**Comment by johlju** [comment]
Sorry, it is not forgotten. I added a bunch of issues in xWebAdministration for hacktoberfest and it has been crazy there with PR's. Last weekend was to busy with family stuff. But I will get to it this weekend I promise! 😄

**Comment by johlju** [comment]
I flagged the e-mail notification so I don't forget! :)

**Comment by X-Guardian** [comment]
Cheers @johlju, no worries!

**Comment by johlju** [comment]
@jcwalker or @gaelcolas can you please merge this one?

**Pull request merged**
