### PR TITLE
SecurityOption: fix NTLM Security Option Names

### PR DESCRIPTION
**Pull request by hackjammer**
#### Pull Request (PR) description
The mapping of the Network Security: Restrict NTLM security options to the underlying reg keys was wrong - this has now been fixed.

Not marking this as a breaking change as I expect it would have been found before if anyone tried to use it!

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/securitypolicydsc/115)

### CODE REVIEW

**Comment by hackjammer** [comment]
Any chance of getting this into the March DSC resource kit release? @kwirkykat 

Thanks!

**Comment by gaelcolas** [comment]
Hey @hackjammer, thanks for the contribution. Will review this and try to release within next resource kit.
;)

**Comment by gaelcolas** [comment]
I'm happy for the changes, although I see this as a breaking change.

You are indeed fixing a bug, and your changes now are configuring the right restrictio

**Comment by gaelcolas** [comment]
After consultation, I'm not flagging this as a breaking change for the following reasons:
- There are no changes in API, and the intent hasn't changed (the config is just fixed)
- Similar fixes haven't received a MAJOR increment for this repository previously
- People should have a test that validates the config before updating a version, so they should pick up this change (and if using this security setting, they should have picked up that issue like @hackjammer did) ;)

Waiting for the build to complete before merging.

**Pull request merged**
