### PR TITLE
Added Network_access_Restrict_clients_allowed_to_make_remote_calls_to_SAM

### LINKED ISSUE #89: Network access: Restrict clients allowed to make remote calls to SAM is not included in module
"Network access: Restrict clients allowed to make remote calls to SAM"
Is not included in the SecurityPolicyDSC module (as far as I can tell)

Reference docs:
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls

https://www.stigviewer.com/stig/windows_10/2017-04-28/finding/V-71769

### PR DESCRIPTION
**Pull request by jcwalker**
#### Pull Request (PR) description
    Added Network_access_Restrict_clients_allowed_to_make_remote_calls_to_SAM to the SecurityOption resource.

#### This Pull Request (PR) fixes the following issues
- Fixes #89 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/securitypolicydsc/106)

### CODE REVIEW

**Comment by jcwalker** [comment]
@johlju can help me out with why this build is failing?  It fails to create a self signed cert.

**Comment by johlju** [comment]
I will try to look at it as soon as I can. :) It has been busy at the day job so haven’t been able to get time for the DSC.

**Comment by johlju** [comment]
Please see this issue: https://github.com/Crypt32/PSPKI/issues/56
When a new release is made by the PSPKI you can kick off the tests again. Alternative chnage appveyor.yml to use a build worker with Windows Server 2016.

**Comment by jcwalker** [comment]
@johlju thanks for following up with me on this.  The build is successfully running in appveyor now.

**Pull request merged**
