### PR TITLE
Release of version 2.3.0.0 of SecurityPolicyDsc

### PR DESCRIPTION
**Pull request by jcwalker**
This change is [Reviewable](https://reviewable.io/reviews/powershell/securitypolicydsc/86)

### CODE REVIEW

**Comment by johlju** [comment]
@jcwalker Is this a release PR for Katie? If so, can we change the PR title? 🙂

**Comment by jcwalker** [comment]
How about "fixed bug where SmbServerNameHardeningLevel policy does not apply correctly"?

**Comment by johlju** [comment]
Sorry didn't mean to be particular of this. Reason for asking is that I looked twice what the PR was doing until I saw it was for merging into master. Was not even sure if this was for Katie or if you merge these yourself, normally Katie do the merging to master, but not sure if the releases for this resource module works differently  🙂 
I was thinking more like "PR for release of version 2.3.0.0" if this PR is for Katie?

**Comment by kwirkykat** [comment]
@jcwalker The master branch only contains the code that has been released to the PowerShell Gallery. PRs from the dev branch to the master branch are considered 'Release PRs'. You don't need to open release PRs. I have a script that takes care of everything needed for the release on release days.
This PR just blocked the script from opening the normal release PR, so I'm hijacking this PR now for this release.

Also, please do not commit any of your changes directly into the dev branch. Even though you have maintainer access, you still need to work from your own fork and submit PRs.

**Pull request merged**
